version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db
  db:
    build: ./database/.docker/mysql
    container_name: database-nest-keycloak
    restart: always
    tty: true
    volumes: 
      - ./database/.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db-nest-keycloak
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - 3306
  